import { defineToolcraft } from "@/toolcraft/runtime";

import {
  BURN_FOIL_SOURCE_TARGET,
  DEFAULT_SOURCE_IMAGE_DATA_URL,
} from "@/burn-foil/burn-foil-settings";

import { appIdentity } from "./app-identity";

const always = { mode: "always" } as const;

export const appSchema = defineToolcraft({
  canvas: {
    draggable: true,
    enabled: true,
    size: { height: 900, unit: "px", width: 900 },
    sizing: { mode: "editable-output" },
    upload: false,
  },
  identity: appIdentity,
  media: {
    defaultAssets: [
      {
        assetKind: "image",
        dataUrl: DEFAULT_SOURCE_IMAGE_DATA_URL,
        fileName: "burn-source.svg",
        id: "default-burn-source",
        mimeType: "image/svg+xml",
        sourceTarget: BURN_FOIL_SOURCE_TARGET,
      },
    ],
  },
  panels: {
    controls: {
      sections: [
        {
          controls: {
            includeBackground: {
              applicability: always,
              defaultValue: true,
              label: "Background",
              performanceReason:
                "The switch changes whether the canvas background contributes to preview and PNG alpha.",
              performanceRole: "responsiveness",
              target: "export.includeBackground",
              type: "switch",
            },
            sceneBackground: {
              applicability: always,
              defaultValue: "#050509",
              label: "Background color",
              performanceReason:
                "The background color changes the visible contrast around transparent burned areas.",
              performanceRole: "responsiveness",
              target: "appearance.background",
              type: "color",
            },
          },
          id: "background",
          title: "Background",
        },
        {
          controls: {
            image: {
              accept: "image/*",
              applicability: always,
              assetKind: "image",
              label: false,
              performanceReason:
                "Uploaded images update the source texture consumed by the shader preview.",
              performanceRole: "responsiveness",
              target: BURN_FOIL_SOURCE_TARGET,
              type: "fileDrop",
            },
            autoCycle: {
              applicability: always,
              defaultValue: false,
              label: "Cycle",
              orderRole: "mode",
              performanceReason:
                "Cycle toggles whether the shader progress advances autonomously.",
              performanceRole: "responsiveness",
              target: "source.autoCycle",
              type: "switch",
            },
            progress: {
              applicability: {
                all: [{ equals: false, target: "source.autoCycle" }],
                mode: "conditional",
              },
              defaultValue: 35,
              label: "Progress",
              max: 100,
              min: 0,
              orderRole: "primary",
              performanceReason:
                "Progress updates the burn-front uniform and should redraw live while dragged.",
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: "source.progress",
              type: "slider",
              unit: "%",
            },
            timeScale: {
              applicability: {
                all: [{ equals: true, target: "source.autoCycle" }],
                mode: "conditional",
              },
              defaultValue: 0.18,
              label: "Cycle speed",
              max: 2,
              min: 0,
              orderRole: "primary",
              performanceReason:
                "Speed changes the autonomous playback increment without changing source resources.",
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 0.01,
              target: "source.timeScale",
              type: "slider",
            },
            opacity: {
              applicability: always,
              defaultValue: 100,
              label: "Opacity",
              max: 100,
              min: 0,
              orderRole: "strength",
              performanceReason:
                "Opacity remaps final shader alpha for the whole burn output.",
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: "source.opacity",
              type: "slider",
              unit: "%",
            },
            tintColor: {
              applicability: always,
              defaultValue: "#FFFFFF",
              label: "Div color",
              orderRole: "color",
              performanceReason:
                "Div color remaps the visible source image color in the shader without changing the source texture.",
              performanceRole: "responsiveness",
              semanticGroup: "source-tint",
              target: "source.tintColor",
              type: "color",
            },
            tintStrength: {
              applicability: always,
              defaultValue: 0,
              label: "Div tint",
              max: 100,
              min: 0,
              orderRole: "strength",
              performanceReason:
                "Div tint controls how strongly the source image is recolored in the shader.",
              performanceRole: "responsiveness",
              semanticGroup: "source-tint",
              sliderValueKind: "continuous",
              step: 1,
              target: "source.tintStrength",
              type: "slider",
              unit: "%",
            },
          },
          id: "source",
          title: "Source",
        },
        {
          controls: {
            startMode: {
              applicability: always,
              defaultValue: "6",
              label: "Start",
              options: [
                { label: "Center", value: "0" },
                { label: "Random point", value: "1" },
                { label: "Left side", value: "2" },
                { label: "Right side", value: "3" },
                { label: "Top side", value: "4" },
                { label: "Bottom side", value: "5" },
                { label: "Random side", value: "6" },
              ],
              orderRole: "mode",
              performanceReason:
                "Start mode changes the burn-distance branch while keeping the same draw pass.",
              performanceRole: "responsiveness",
              target: "burn.startMode",
              type: "select",
            },
            randomSeed: {
              applicability: always,
              defaultValue: 12,
              label: "Seed",
              max: 9999,
              min: 0,
              orderRole: "mode",
              performanceReason:
                "Seed changes the random origin or side branch used by the burn mask.",
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: "burn.randomSeed",
              type: "slider",
            },
            centerX: {
              applicability: {
                all: [{ oneOf: ["0"], target: "burn.startMode" }],
                mode: "conditional",
              },
              defaultValue: 50,
              label: "Center X",
              max: 100,
              min: 0,
              orderRole: "spatial",
              performanceReason:
                "Center X moves the circular burn origin in the shader.",
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: "burn.centerX",
              type: "slider",
              unit: "%",
            },
            centerY: {
              applicability: {
                all: [{ oneOf: ["0"], target: "burn.startMode" }],
                mode: "conditional",
              },
              defaultValue: 52,
              label: "Center Y",
              max: 100,
              min: 0,
              orderRole: "spatial",
              performanceReason:
                "Center Y moves the circular burn origin in the shader.",
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: "burn.centerY",
              type: "slider",
              unit: "%",
            },
            burnWidth: {
              applicability: always,
              defaultValue: 9,
              label: "Burn width",
              max: 35,
              min: 0.5,
              orderRole: "detail",
              performanceReason:
                "Burn width changes the alpha threshold band around the burn front.",
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 0.5,
              target: "burn.width",
              type: "slider",
              unit: "%",
            },
          },
          id: "burn-shape",
          title: "Burn Shape",
        },
        {
          controls: {
            emberWidth: {
              applicability: always,
              defaultValue: 2.5,
              label: "Ember width",
              max: 18,
              min: 0.2,
              orderRole: "detail",
              performanceReason:
                "Ember width controls the visible fire band around the burn front.",
              performanceRole: "responsiveness",
              semanticGroup: "fire-band",
              sliderValueKind: "continuous",
              step: 0.1,
              target: "fire.emberWidth",
              type: "slider",
              unit: "%",
            },
            flameSize: {
              applicability: always,
              defaultValue: 130,
              label: "Fire size",
              max: 300,
              min: 25,
              orderRole: "strength",
              performanceReason:
                "Fire size widens the orange flame band around the burn front.",
              performanceRole: "responsiveness",
              semanticGroup: "fire-band",
              sliderValueKind: "continuous",
              step: 5,
              target: "fire.flameSize",
              type: "slider",
              unit: "%",
            },
            noiseScale: {
              applicability: always,
              defaultValue: 18,
              label: "Noise scale",
              max: 80,
              min: 1,
              orderRole: "detail",
              performanceReason:
                "Noise scale changes the ragged flame field frequency.",
              performanceRole: "responsiveness",
              semanticGroup: "fire-band",
              sliderValueKind: "continuous",
              step: 1,
              target: "fire.noiseScale",
              type: "slider",
            },
            edgeGlow: {
              applicability: always,
              defaultValue: 55,
              label: "Edge glow",
              max: 100,
              min: 0,
              orderRole: "strength",
              performanceReason:
                "Edge glow changes fire intensity and the edge emission uniform.",
              performanceRole: "responsiveness",
              semanticGroup: "fire-band",
              sliderValueKind: "continuous",
              step: 1,
              target: "fire.edgeGlow",
              type: "slider",
              unit: "%",
            },
            fireIntensity: {
              applicability: always,
              defaultValue: 125,
              label: "Fire intensity",
              max: 250,
              min: 0,
              orderRole: "strength",
              performanceReason:
                "Fire intensity multiplies the visible burn emission and rim brightness.",
              performanceRole: "responsiveness",
              semanticGroup: "fire-band",
              sliderValueKind: "continuous",
              step: 5,
              target: "fire.intensity",
              type: "slider",
              unit: "%",
            },
            trailStrength: {
              applicability: always,
              defaultValue: 115,
              label: "Trail strength",
              max: 250,
              min: 0,
              orderRole: "strength",
              performanceReason:
                "Trail strength controls how strongly the selected trail color tints the burned residue.",
              performanceRole: "responsiveness",
              semanticGroup: "fire-band",
              sliderValueKind: "continuous",
              step: 5,
              target: "fire.trailStrength",
              type: "slider",
              unit: "%",
            },
            trailColor: {
              applicability: always,
              defaultValue: "#A33212",
              label: "Trail",
              orderRole: "color",
              performanceReason:
                "Trail color updates the soft burn residue glow around the edge.",
              performanceRole: "responsiveness",
              semanticGroup: "fire-palette",
              target: "fire.trailColor",
              type: "color",
            },
            emberColor: {
              applicability: always,
              defaultValue: "#B91208",
              label: "Ember",
              orderRole: "color",
              performanceReason:
                "Ember color updates the low-temperature burn ramp.",
              performanceRole: "responsiveness",
              semanticGroup: "fire-palette",
              target: "fire.emberColor",
              type: "color",
            },
            fireColor: {
              applicability: always,
              defaultValue: "#FF580C",
              label: "Fire",
              orderRole: "color",
              performanceReason:
                "Fire color updates the mid-temperature burn ramp.",
              performanceRole: "responsiveness",
              semanticGroup: "fire-palette",
              target: "fire.fireColor",
              type: "color",
            },
            hotColor: {
              applicability: always,
              defaultValue: "#FFF69A",
              label: "Hot",
              orderRole: "color",
              performanceReason:
                "Hot color updates the bright core of the burn edge.",
              performanceRole: "responsiveness",
              semanticGroup: "fire-palette",
              target: "fire.hotColor",
              type: "color",
            },
          },
          id: "fire-detail",
          title: "Fire Detail",
        },
        {
          controls: {
            lightStrength: {
              applicability: always,
              defaultValue: 45,
              label: "Light intensity",
              max: 200,
              min: 0,
              orderRole: "strength",
              performanceReason:
                "Light controls the halo strength around the active burn edge.",
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: "light.strength",
              type: "slider",
              unit: "%",
            },
            glowRadius: {
              applicability: always,
              defaultValue: 22,
              label: "Glow radius",
              max: 100,
              min: 5,
              orderRole: "strength",
              performanceReason:
                "Glow radius widens the fire halo without changing image upload cost.",
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: "light.glowRadius",
              type: "slider",
              unit: "%",
            },
            bloomStrength: {
              applicability: always,
              defaultValue: 28,
              label: "Bloom",
              max: 100,
              min: 0,
              orderRole: "strength",
              performanceReason:
                "Bloom adds a soft emission layer around the active burn band.",
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: "light.bloomStrength",
              type: "slider",
              unit: "%",
            },
            bloomRadius: {
              applicability: always,
              defaultValue: 22,
              label: "Bloom radius",
              max: 100,
              min: 5,
              orderRole: "strength",
              performanceReason:
                "Bloom radius controls how far the soft emission spreads.",
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: "light.bloomRadius",
              type: "slider",
              unit: "%",
            },
            distortionStrength: {
              applicability: always,
              defaultValue: 36,
              label: "Distortion",
              max: 100,
              min: 0,
              orderRole: "detail",
              performanceReason:
                "Distortion bends the source image near the heat edge.",
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: "heat.distortionStrength",
              type: "slider",
              unit: "%",
            },
            distortionSize: {
              applicability: always,
              defaultValue: 35,
              label: "Distortion size",
              max: 100,
              min: 5,
              orderRole: "detail",
              performanceReason:
                "Distortion size widens the heat-warp area around the burn front.",
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: "heat.distortionSize",
              type: "slider",
              unit: "%",
            },
          },
          id: "heat-light",
          title: "Heat And Light",
        },
        {
          controls: {
            qualityPreset: {
              applicability: always,
              defaultValue: "lite",
              label: "Shader",
              options: [
                { label: "Lite", value: "lite" },
                { label: "Full", value: "full" },
              ],
              orderRole: "mode",
              performanceReason:
                "Shader selects the compiled fragment variant so tuning can compare lighter and full-quality burn logic.",
              performanceRole: "workload",
              target: "shader.qualityPreset",
              type: "select",
            },
            maxPixelSize: {
              applicability: always,
              defaultValue: 1280,
              label: "Max pixels",
              max: 2400,
              min: 640,
              orderRole: "strength",
              performanceReason:
                "Max pixels caps preview backing resolution and directly bounds fragment shader cost.",
              performanceRole: "workload",
              sliderValueKind: "continuous",
              step: 80,
              target: "performance.maxPixelSize",
              type: "slider",
              unit: "px",
            },
          },
          id: "quality",
          layoutGroups: [
            { columns: 2, controls: ["qualityPreset", "maxPixelSize"], layout: "inline" },
          ],
          title: "Quality",
        },
        {
          controls: {
            format: {
              applicability: always,
              defaultValue: "png",
              label: "Format",
              options: [
                { label: "PNG", value: "png" },
                { label: "JPG", value: "jpg" },
              ],
              performanceReason:
                "Format changes the runtime image export encoder path.",
              performanceRole: "responsiveness",
              target: "export.image.format",
              type: "select",
            },
            resolution: {
              applicability: always,
              defaultValue: "4k",
              label: "Resolution",
              options: [
                { label: "2K", value: "2k" },
                { label: "4K", value: "4k" },
                { label: "8K", value: "8k" },
              ],
              performanceReason:
                "Resolution changes the runtime-selected PNG output dimensions.",
              performanceRole: "responsiveness",
              target: "export.image.resolution",
              type: "select",
            },
          },
          id: "image-export",
          layoutGroups: [
            { columns: 2, controls: ["format", "resolution"], layout: "inline" },
          ],
          title: "Image Export",
        },
        {
          actionGroup: "primary",
          controls: {
            export: {
              actions: [
                {
                  icon: "upload-simple",
                  label: "Export PNG",
                  role: "export-image",
                  value: "export.image",
                },
              ],
              applicability: always,
              target: "actions.export",
              type: "panelActions",
            },
          },
          id: "export-actions",
        },
      ],
      title: "Burn Controls",
    },
  },
  settingsTransfer: { enabled: "auto", fileName: "burn-foil-settings" },
  toolbar: {
    history: true,
    radar: true,
    theme: true,
    zoom: true,
  },
});
